drop table if exists category CASCADE;
drop table if exists product CASCADE;
create table category (id bigint generated by default as identity, name varchar(255), primary key (id));
create table product (id bigint generated by default as identity, description varchar(255), image varchar(255), price double, title varchar(255), category_id bigint, primary key (id));
alter table product add constraint Ecomerce foreign key (category_id) references category;

INSERT INTO category (id, name) VALUES ( null, 'perfumaria');
--
INSERT INTO product ( id, title, price, category_id, description, image) VALUES ( null, 'Essencial Supreme Deo Parfum', 117.9, 1, 'Combinação entre o patchouli, amadeirado intenso, com a sensualidade e o calor do ishpink, a canela amazônica', 'https://static.natura.com/cdn/ff/CG4lbHLHtt_3S9uQLiRKySVdijdDScjwkPaNJ8AQIjI/1620755547/public/2021-05/95560_caminho_olfativo.jpg');
INSERT INTO product ( id, title, price, category_id, description, image) VALUES ( null, 'Essencial Supreme Deo Parfum', 118.9, 1, 'Combinação entre o patchouli, amadeirado intenso, com a sensualidade e o calor do ishpink, a canela amazônica', 'https://static.natura.com/cdn/ff/CG4lbHLHtt_3S9uQLiRKySVdijdDScjwkPaNJ8AQIjI/1620755547/public/2021-05/95560_caminho_olfativo.jpg');
INSERT INTO product ( id, title, price, category_id, description, image) VALUES ( null, 'Essencial Supreme Deo Parfum', 119.9, 1, 'Combinação entre o patchouli, amadeirado intenso, com a sensualidade e o calor do ishpink, a canela amazônica', 'https://static.natura.com/cdn/ff/CG4lbHLHtt_3S9uQLiRKySVdijdDScjwkPaNJ8AQIjI/1620755547/public/2021-05/95560_caminho_olfativo.jpg');
INSERT INTO product ( id, title, price, category_id, description, image) VALUES ( null, 'Essencial Supreme Deo Parfum', 120.9, 1, 'Combinação entre o patchouli, amadeirado intenso, com a sensualidade e o calor do ishpink, a canela amazônica', 'https://static.natura.com/cdn/ff/CG4lbHLHtt_3S9uQLiRKySVdijdDScjwkPaNJ8AQIjI/1620755547/public/2021-05/95560_caminho_olfativo.jpg');
INSERT INTO product ( id, title, price, category_id, description, image) VALUES ( null, 'Essencial Supreme Deo Parfum', 121.9, 1, 'Combinação entre o patchouli, amadeirado intenso, com a sensualidade e o calor do ishpink, a canela amazônica', 'https://static.natura.com/cdn/ff/CG4lbHLHtt_3S9uQLiRKySVdijdDScjwkPaNJ8AQIjI/1620755547/public/2021-05/95560_caminho_olfativo.jpg');
INSERT INTO product ( id, title, price, category_id, description, image) VALUES ( null, 'Essencial Supreme Deo Parfum', 122.9, 1, 'Combinação entre o patchouli, amadeirado intenso, com a sensualidade e o calor do ishpink, a canela amazônica', 'https://static.natura.com/cdn/ff/CG4lbHLHtt_3S9uQLiRKySVdijdDScjwkPaNJ8AQIjI/1620755547/public/2021-05/95560_caminho_olfativo.jpg');

